import js from '@eslint/js';
import ts from 'typescript-eslint';
import svelte from 'eslint-plugin-svelte';
import importX from 'eslint-plugin-import-x';
import globals from 'globals';
import svelteConfig from './svelte.config.js';

export default ts.config(
  {
    ignores: [
      'dist/',
      'dev-dist/',
      'coverage/',
      // Linked worktrees parked under the repo look like extra source trees to a
      // scan launched from the main checkout (and their own tsconfig.json breaks
      // tsconfigRootDir auto-detection). Ignore them.
      '.pi/worktrees/**',
      '.claude/**',
      // Throwaway probes, which are meant to be written fast and deleted. Linting
      // them turns the gate red for a file that is not part of the project — and
      // a stale one left behind makes `npm run lint` look broken on a clean tree.
      'scripts/tmp-*',
    ],
  },
  js.configs.recommended,
  ts.configs.recommended,
  svelte.configs.recommended,
  {
    languageOptions: {
      globals: { ...globals.browser },
      // Pin the root so typescript-eslint doesn't auto-detect multiple
      // candidates when linked worktrees (each with their own tsconfig.json)
      // are checked out under the repo.
      parserOptions: { tsconfigRootDir: import.meta.dirname },
    },
    rules: {
      'no-restricted-imports': [
        'error',
        {
          paths: [
            {
              name: 'uuid',
              message: 'IDs are client-generated by newId() in src/lib/ids.ts. Do not install uuid.',
            },
          ],
        },
      ],
    },
  },
  {
    files: ['**/*.svelte', '**/*.svelte.ts', '**/*.svelte.js'],
    languageOptions: {
      parserOptions: {
        parser: ts.parser,
        extraFileExtensions: ['.svelte'],
        svelteConfig,
      },
    },
  },
  {
    // Not the test files. They open with `import '../api/testUtils'`, whose
    // stubs for fetch/Request/localStorage have to be installed before anything
    // that reads them is imported — a parent import that must precede the
    // package ones. That is the whole of the rule's disagreement with this
    // codebase: 75 of the 76 files it flagged were tests obeying that rule.
    ignores: ['**/*.test.ts'],
    plugins: { 'import-x': importX },
    rules: {
      // Groups only, deliberately not alphabetized. What this buys is that a
      // package import cannot hide in the middle of a run of local ones — the
      // ordering question that actually costs a reader something, and the one
      // real violation it found. Sorting within a group as well would rewrite
      // the import block of almost every file in src/ for no reading benefit,
      // and collide with every branch currently open.
      'import-x/order': [
        'error',
        {
          groups: [['builtin', 'external'], 'internal', ['parent', 'sibling', 'index']],
          'newlines-between': 'never',
        },
      ],
    },
  },
  {
    files: ['scripts/**/*.mjs'],
    languageOptions: {
      globals: { ...globals.node },
    },
  }
);
