import js from '@eslint/js';
import ts from 'typescript-eslint';
import svelte from 'eslint-plugin-svelte';
import importX from 'eslint-plugin-import-x';
import globals from 'globals';
import svelteConfig from './svelte.config.js';

const VOID_STORE_STUB =
  'Delete this stub and let the store method run. A stub supplying a return the fixture cannot ' +
  'produce (mockResolvedValue(task), mockReturnValue(false), mockImplementation) is legitimate; ' +
  'this one only suppresses the method, so the test proves a call happened and nothing proves ' +
  'the method does anything. What it does NOT buy: calling through is not coverage — a spy ' +
  'asserting only toHaveBeenCalledWith still passes when the store method is broken, so behaviour ' +
  'belongs in the store test (src/lib/*.test.ts). What it does buy: a fixture lying to the store ' +
  'fails loudly instead of being absorbed, and no reader mistakes a suppressed method for a tested one.';

// The store objects whose mutations this applies to. Spying is fine; only the
// void-valued replacement is not.
const STORES = '/^(board|awayBoard|projects|session|outbox)$/';

const spiedStoreMethod = `[callee.object.callee.object.name='vi'][callee.object.callee.property.name='spyOn'][callee.object.arguments.0.name=${STORES}]`;

// Groups only, deliberately not alphabetized. What this buys is that a package
// import cannot hide in the middle of a run of local ones — the ordering
// question that actually costs a reader something, and the one real violation
// it found. Sorting within a group as well would rewrite the import block of
// almost every file in src/ for no reading benefit, and collide with every
// branch currently open.
const IMPORT_GROUPS = [['builtin', 'external'], 'internal', ['parent', 'sibling', 'index']];

// Every specifier the test files reach api/testUtils by. Literal, not a glob:
// minimatch will not cross a `..` segment, so `**/api/testUtils` matches none of
// these and every test file goes back to being flagged.
const TEST_UTILS_FIRST = ['../api/testUtils', './api/testUtils', './testUtils'].map((pattern) => ({
  pattern,
  group: 'builtin',
  position: 'before',
}));

export default ts.config(
  {
    ignores: [
      'dist/',
      'dev-dist/',
      'coverage/',
      // Linked worktrees parked under the repo look like extra source trees to a
      // scan launched from the main checkout (and their own tsconfig.json breaks
      // tsconfigRootDir auto-detection). Ignore them.
      '.pi/worktrees/**',
      '.claude/**',
      // Throwaway probes, which are meant to be written fast and deleted. Linting
      // them turns the gate red for a file that is not part of the project — and
      // a stale one left behind makes `pnpm run lint` look broken on a clean tree.
      'scripts/tmp-*',
    ],
  },
  js.configs.recommended,
  ts.configs.recommended,
  svelte.configs.recommended,
  {
    languageOptions: {
      globals: { ...globals.browser },
      // Pin the root so typescript-eslint doesn't auto-detect multiple
      // candidates when linked worktrees (each with their own tsconfig.json)
      // are checked out under the repo.
      parserOptions: { tsconfigRootDir: import.meta.dirname },
    },
    rules: {
      'no-restricted-imports': [
        'error',
        {
          paths: [
            {
              name: 'uuid',
              message: 'IDs are client-generated by newId() in src/lib/ids.ts. Do not install uuid.',
            },
          ],
        },
      ],
    },
  },
  {
    files: ['**/*.svelte', '**/*.svelte.ts', '**/*.svelte.js'],
    languageOptions: {
      parserOptions: {
        parser: ts.parser,
        extraFileExtensions: ['.svelte'],
        svelteConfig,
      },
    },
  },
  {
    // Not the test files, which take the same rule plus the testUtils pin
    // below. The split is what keeps `warnOnUnassignedImports` off this block:
    // src/vitest-setup.ts opens with three side-effect imports in a deliberate
    // order that the pin would object to.
    ignores: ['**/*.test.ts'],
    plugins: { 'import-x': importX },
    rules: {
      'import-x/order': ['error', { groups: IMPORT_GROUPS, 'newlines-between': 'never' }],
    },
  },
  {
    files: ['**/*.test.ts'],
    plugins: { 'import-x': importX },
    rules: {
      // Ranking api/testUtils ahead of the packages is what lets the tests take
      // the rule at all — see the Tests section of CLAUDE.md for why it loads
      // first. Without the pin the rule flags every test file that obeys that
      // convention, and the autofix "resolves" them by moving the stubs below
      // the packages they exist to precede.
      'import-x/order': [
        'error',
        {
          groups: IMPORT_GROUPS,
          pathGroups: TEST_UTILS_FIRST,
          pathGroupsExcludedImportTypes: [],
          // The bare `import '../api/testUtils'` form is an unassigned import,
          // which the rule ignores by default. Reporting it costs nothing here —
          // testUtils is the only side-effect import in any test file — but the
          // fixer still will not move it, since reordering a side effect can
          // change what a module does. That one is reported and fixed by hand.
          warnOnUnassignedImports: true,
          'newlines-between': 'never',
        },
      ],
    },
  },
  {
    // The UI layer, wherever it lives: `shortcuts.svelte.ts` drives the same
    // store mutations a component does and its test reached for the same stub.
    // A store's own test is deliberately out of scope — suppressing a *sibling*
    // store there is how a unit under test gets isolated.
    files: ['src/components/**/*.test.ts', 'src/routes/**/*.test.ts', 'src/lib/shortcuts.test.ts'],
    rules: {
      'no-restricted-syntax': [
        'error',
        {
          selector: `CallExpression[callee.property.name='mockResolvedValue'][arguments.length=0]${spiedStoreMethod}`,
          message: VOID_STORE_STUB,
        },
        {
          // `[arguments.0.type='Identifier']` must precede the name test: esquery
          // compares a missing `.name` against the string 'undefined' and finds
          // them equal, so without it this also matches `mockResolvedValue(true)`.
          selector: `CallExpression[callee.property.name='mockResolvedValue'][arguments.length=1][arguments.0.type='Identifier'][arguments.0.name='undefined']${spiedStoreMethod}`,
          message: VOID_STORE_STUB,
        },
      ],
    },
  },
  {
    files: ['scripts/**/*.mjs'],
    languageOptions: {
      globals: { ...globals.node },
    },
  }
);
